// Slice 50 — real-Go engine oracle replay.
// Fixture: go-slice50-engine-reference.json, generated by
// internal/engine/go_slice50_engine_oracle_test.go.
import { describe, it as bunIt, expect } from 'bun:test';
import { readFileSync } from 'node:fs';

import { Graph } from '../../src/graph/graph.js';
import { Node } from '../../src/graph/node.js';
import { Label } from '../../src/graph/label.js';
import { Point } from '../../src/geometry/point.js';
import { backgroundWorkContext } from '../../src/limits/work-context.js';
import { EvaluateWithArea } from '../../src/quality/scoring.js';
import { Layout, LayoutOptions } from '../../src/engine/pipeline.js';
import { CompoundCandidate, compoundCrossAxisDetours } from '../../src/engine/compound-candidate.js';
import { PreserveCompoundRoutes } from '../../src/engine/compound-routes.js';

const it = (name, fn) => bunIt(name, fn, 300_000);
const fixture = JSON.parse(readFileSync(new URL('../fixtures/go-slice50-engine-reference.json', import.meta.url), 'utf8'));
const bg = backgroundWorkContext();

function makeLabel(spec) {
  const label = new Label(spec.text, spec.w, spec.h);
  label.Position = spec.pos ?? 0;
  if (spec.fixed) label.FixPosition();
  return label;
}

export function buildEngineSpec(spec) {
  const g = new Graph();
  const nodes = new Map();
  for (const ns of spec.nodes ?? []) {
    const n = new Node(BigInt(ns.id), ns.w, ns.h);
    if (ns.shape) n.SetShape(ns.shape);
    if (ns.fixed) n.FixedTopLeft = new Point(ns.fx ?? 0, ns.fy ?? 0);
    if (ns.label) n.Label = makeLabel(ns.label);
    g.AddNewNodeToContainer(ns.container ? nodes.get(ns.container) : null, n);
    nodes.set(ns.id, n);
  }
  for (const es of spec.edges ?? []) {
    const e = g.Connect(nodes.get(es.from), nodes.get(es.to));
    e.ID = BigInt(es.id);
    if (es.directed) {
      e.SourceArrowhead = 'none';
      e.TargetArrowhead = 'triangle';
    }
    if (es.label) e.Label = makeLabel(es.label);
  }
  for (const d of spec.directions ?? []) {
    g.Directions.set(d.container ? nodes.get(d.container) : null, d.orientation);
  }
  return g;
}

function snapshot(graph) {
  return JSON.stringify(graph.Nodes.map((n) => [String(n.ID), n.TopLeft?.X ?? null, n.TopLeft?.Y ?? null, n.Width, n.Height]))
    + JSON.stringify(graph.Edges.map((e) => [String(e.ID), e.Points.length]));
}

function runCase(spec, seed) {
  const input = buildEngineSpec(spec);
  const before = snapshot(input);
  const out = Layout(bg, input, new LayoutOptions({ Seed: BigInt(seed) }));
  expect(snapshot(input)).toBe(before);
  expect(out).not.toBe(input);
  const result = { seed, error: '', nodes: [], edges: [], area: 0, penalty: 0 };
  if (out.Nodes.length === 0) result.empty = true;
  for (const n of out.Nodes) {
    result.nodes.push({
      id: Number(n.ID), x: n.TopLeft?.X ?? 0, y: n.TopLeft?.Y ?? 0, w: n.Width, h: n.Height,
      labelPos: n.Label != null ? n.Label.Position : 0,
    });
  }
  for (const e of out.Edges) {
    const points = [];
    for (const p of e.Points) points.push(p.X, p.Y);
    result.edges.push({
      id: Number(e.ID), points, isCurve: Boolean(e.IsCurve),
      labelPos: e.Label != null ? e.Label.Position : 0, labelPercentage: e.LabelPercentage,
    });
  }
  if (out.Nodes.length > 0) {
    const scored = EvaluateWithArea(bg, out);
    result.penalty = scored.penalty;
    result.area = scored.area;
  }
  return result;
}

function normalizeExpected(expected) {
  return {
    seed: expected.seed,
    error: expected.error,
    nodes: expected.nodes ?? [],
    edges: (expected.edges ?? []).map((e) => ({ ...e, points: e.points ?? [] })),
    area: expected.area,
    penalty: expected.penalty,
    ...(expected.empty ? { empty: true } : {}),
  };
}

describe('Slice 50 — engine.Layout matches pinned Go', () => {
  for (const c of fixture.cases) {
    for (const expected of c.results) {
      it(`${c.name} seed ${expected.seed}`, () => {
        const actual = runCase(c.spec, expected.seed);
        expect(actual).toEqual(normalizeExpected(expected));
        // Determinism: a second run is identical.
        expect(runCase(c.spec, expected.seed)).toEqual(actual);
      });
    }
  }
});

function capture(out) {
  const result = { seed: 0, error: '', nodes: [], edges: [], area: 0, penalty: 0 };
  for (const n of out.Nodes) {
    result.nodes.push({ id: Number(n.ID), x: n.TopLeft?.X ?? 0, y: n.TopLeft?.Y ?? 0, w: n.Width, h: n.Height, labelPos: n.Label != null ? n.Label.Position : 0 });
  }
  for (const e of out.Edges) {
    const points = [];
    for (const p of e.Points) points.push(p.X, p.Y);
    result.edges.push({ id: Number(e.ID), points, isCurve: Boolean(e.IsCurve), labelPos: e.Label != null ? e.Label.Position : 0, labelPercentage: e.LabelPercentage });
  }
  return result;
}

describe('Slice 50 — compound candidate and route preservation match pinned Go', () => {
  for (const c of fixture.compound) {
    it(c.name, () => {
      const ordinary = Layout(bg, buildEngineSpec(c.spec), new LayoutOptions({ Seed: BigInt(c.seed) }));
      const before = JSON.stringify(capture(ordinary));
      const candidate = CompoundCandidate(bg, ordinary);
      expect(JSON.stringify(capture(ordinary))).toBe(before);
      expect(candidate !== ordinary).toBe(c.changed);
      expect([compoundCrossAxisDetours(ordinary), compoundCrossAxisDetours(candidate)]).toEqual(c.detours);
      if (c.changed) {
        expect(capture(candidate)).toEqual(normalizeExpected(c.candidate));
        const candidateBefore = JSON.stringify(capture(candidate));
        const preserved = PreserveCompoundRoutes(bg, ordinary, candidate);
        expect(preserved).not.toBe(candidate);
        expect(JSON.stringify(capture(candidate))).toBe(candidateBefore);
        expect(JSON.stringify(capture(ordinary))).toBe(before);
        expect(capture(preserved)).toEqual(normalizeExpected(c.preserved));
      }
    });
  }
});
