/**
 * node-placement-cost-oracle.test.js
 *
 * Go oracle replay for Slice 41: Node Placement-Cost Kernel Bundle.
 * Validates JS implementation parity against the fixture generated by
 * internal/placementcost/go_node_placement_cost_oracle_test.go.
 *
 * Pinned Go: 01bc7ecdbdd04c13d6fe5df1967d2d9aa14ae579
 * Pinned slice branch: tala-js/slice-41-placement-cost-kernel
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { Graph } from '../../src/graph/graph.js';
import { Node } from '../../src/graph/node.js';
import { Cluster } from '../../src/graph/cluster.js';
import { EdgeAbduction } from '../../src/graph/edge-abduction.js';
import { Point } from '../../src/geometry/point.js';

import {
  directionCompass,
  compassDelta,
  compassAxisDelta,
  placementDistance,
  distanceToPoint,
  sizelessOrientation,
  depth,
} from '../../src/placementcost/geometry.js';
import { axisScore } from '../../src/placementcost/axis.js';
import { clusterExactlyTwoExternalConnectedNodes } from '../../src/placementcost/cluster.js';
import { scoringNodeBounds } from '../../src/placementcost/obstruction-bounds.js';
import { flowContinuityCost } from '../../src/placementcost/flow-continuity.js';
import { NodeSymmetry, ColumnCrossingCost } from '../../src/placementcost/symmetry.js';
import { NodeEdgeLength, EdgeLengthOptions } from '../../src/placementcost/edge-length.js';
import { NewNodeEdgeLengthScorer } from '../../src/placementcost/edge-length-scorer.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const fixturePath = path.join(__dirname, '..', 'fixtures', 'go-node-placement-cost-reference.json');
const reference = JSON.parse(fs.readFileSync(fixturePath, 'utf8'));

// ── helpers ──────────────────────────────────────────────────────────────────

let _id = 1n;

function createTestGraph() {
  const g = new Graph();
  g.Containers = new Map();
  g.CellSize = 20.0;
  return g;
}

function addTestNode(g, x, y, w, h) {
  const n = new Node(_id++, w, h);
  n.TopLeft = new Point(x, y);
  g.addNodeUnchecked(n);
  return n;
}

class CountingContext {
  constructor(cancelAt) {
    this.cancelAt = cancelAt;
    this.count = 0;
  }
  Err() {
    this.count++;
    if (this.cancelAt > 0 && this.count >= this.cancelAt) {
      return new Error('context canceled');
    }
    return null;
  }
}

const NULL_CTX = { Err() { return null; } };

// ── 1. Layoutgraph accessor additions ────────────────────────────────────────

describe('Slice 41 Node Placement-Cost Kernel — Go Oracle', () => {
  describe('1. Layoutgraph accessor additions', () => {

    it('center_normal', () => {
      _id = 1n;
      const g = createTestGraph();
      const n1 = addTestNode(g, 100, 200, 80, 40);
      const c = n1.Center();
      const exp = reference.layoutgraphAccessors.find(s => s.name === 'center_normal');
      assert.equal(c.X, exp.center.x);
      assert.equal(c.Y, exp.center.y);
    });

    it('center_negative', () => {
      _id = 100n;
      const g = createTestGraph();
      const n1 = addTestNode(g, -50, -30, 10, 20);
      const c = n1.Center();
      const exp = reference.layoutgraphAccessors.find(s => s.name === 'center_negative');
      assert.equal(c.X, exp.center.x);
      assert.equal(c.Y, exp.center.y);
    });

    const orientScenarios = [
      { name: 'top_left',     tl: [0, 0],     w: 50, h: 50 },
      { name: 'top',          tl: [120, 0],   w: 50, h: 50 },
      { name: 'top_right',    tl: [250, 0],   w: 50, h: 50 },
      { name: 'left',         tl: [0, 120],   w: 50, h: 50 },
      { name: 'right',        tl: [250, 120], w: 50, h: 50 },
      { name: 'bottom_left',  tl: [0, 250],   w: 50, h: 50 },
      { name: 'bottom',       tl: [120, 250], w: 50, h: 50 },
      { name: 'bottom_right', tl: [250, 250], w: 50, h: 50 },
      { name: 'overlap',      tl: [150, 150], w: 50, h: 50 },
      { name: 'unpositioned', tl: null,       w: 50, h: 50 },
    ];

    for (const s of orientScenarios) {
      it(`orientation_${s.name}`, () => {
        _id = 200n;
        const g = createTestGraph();
        const center = addTestNode(g, 100, 100, 100, 100);
        const other = new Node(_id++, s.w, s.h);
        other.TopLeft = s.tl ? new Point(s.tl[0], s.tl[1]) : null;
        g.addNodeUnchecked(other);
        const o = other.Orientation(center);
        const exp = reference.layoutgraphAccessors.find(sc => sc.name === `orientation_${s.name}`);
        assert.equal(Number(o), exp.orientation ?? 0);
      });
    }

    const overlapLineCases = [
      { name: 'cross_through',     p1: [50, 150], p2: [250, 150], d: 0  },
      { name: 'touch_border',      p1: [50, 100], p2: [80, 100],  d: 0  },
      { name: 'outside',           p1: [50, 50],  p2: [80, 50],   d: 0  },
      { name: 'endpoint_inside',   p1: [150, 150], p2: [300, 300], d: 0  },
      { name: 'padded_delta_hit',  p1: [95, 50],  p2: [95, 95],   d: 10 },
      { name: 'padded_delta_miss', p1: [80, 50],  p2: [80, 80],   d: 10 },
    ];

    for (const c of overlapLineCases) {
      it(`overlaps_line_${c.name}`, () => {
        _id = 300n;
        const g = createTestGraph();
        const n = addTestNode(g, 100, 100, 100, 100);
        const res = n.OverlapsLine(new Point(c.p1[0], c.p1[1]), new Point(c.p2[0], c.p2[1]), c.d);
        const exp = reference.layoutgraphAccessors.find(s => s.name === `overlaps_line_${c.name}`);
        assert.equal(res, exp.overlapsLine);
      });
    }

    const passesThroughCases = [
      { name: 'cross_straight', p1: [50, 150], p2: [250, 150] },
      { name: 'cross_diagonal', p1: [50, 50],  p2: [250, 250] },
      { name: 'miss_above',     p1: [50, 50],  p2: [250, 50]  },
      { name: 'touch_corner',   p1: [50, 100], p2: [100, 50]  },
    ];

    for (const c of passesThroughCases) {
      it(`passes_through_${c.name}`, () => {
        _id = 400n;
        const g = createTestGraph();
        const n = addTestNode(g, 100, 100, 100, 100);
        const res = n.PassesThrough(new Point(c.p1[0], c.p1[1]), new Point(c.p2[0], c.p2[1]));
        const exp = reference.layoutgraphAccessors.find(s => s.name === `passes_through_${c.name}`);
        assert.equal(res, exp.passesThrough);
      });
    }

    it('area_normal', () => {
      _id = 500n;
      const g = createTestGraph();
      const n1 = addTestNode(g, 10, 20, 40, 60);
      const exp = reference.layoutgraphAccessors.find(s => s.name === 'area_normal');
      assert.equal(n1.Area(), exp.area);
    });

    const dimCases = [
      { name: 'overlaps_dim_h_with_sizes',    horiz: true,  sizes: true  },
      { name: 'overlaps_dim_h_without_sizes', horiz: true,  sizes: false },
      { name: 'overlaps_dim_v_with_sizes',    horiz: false, sizes: true  },
      { name: 'overlaps_dim_v_without_sizes', horiz: false, sizes: false },
    ];

    for (const dc of dimCases) {
      it(dc.name, () => {
        _id = 600n;
        const g = createTestGraph();
        const n1 = addTestNode(g, 10, 20, 40, 60);
        const n2 = addTestNode(g, 30, 50, 50, 50);
        const res = n1.OverlapsAlongDimension(n2, dc.horiz, dc.sizes);
        const exp = reference.layoutgraphAccessors.find(s => s.name === dc.name);
        assert.equal(res, exp.overlapsDim);
      });
    }

    it('edge_table_columns_facing_ports', () => {
      _id = 700n;
      const g = createTestGraph();
      const table1 = addTestNode(g, 100, 100, 120, 200);
      table1.SetShape('Table');
      table1.SetNumColumns(4);
      const table2 = addTestNode(g, 400, 100, 120, 200);
      table2.SetShape('Table');
      table2.SetNumColumns(4);

      const e = g.Connect(table1, table2);
      e.FromTableColumnIndex = 0;
      e.ToTableColumnIndex = 2;

      const [fp, tp, hasF, hasT, orient] = e.FacingTablePortValues(null, null);
      const hasCol = e.HasTableColumn();
      const betweenCol = e.IsBetweenTableColumns();

      const exp = reference.layoutgraphAccessors.find(s => s.name === 'edge_table_columns_facing_ports');
      assert.equal(fp.X, exp.facingFromPort.x, 'facingFromPort.X');
      assert.equal(fp.Y, exp.facingFromPort.y, 'facingFromPort.Y');
      assert.equal(tp.X, exp.facingToPort.x, 'facingToPort.X');
      assert.equal(tp.Y, exp.facingToPort.y, 'facingToPort.Y');
      assert.equal(hasF, exp.hasFacingFrom, 'hasFacingFrom');
      assert.equal(hasT, exp.hasFacingTo, 'hasFacingTo');
      assert.equal(Number(orient), exp.facingOrient, 'facingOrient');
      assert.equal(hasCol, exp.hasTableCol, 'hasTableCol');
      assert.equal(betweenCol, exp.betweenTableCol, 'betweenTableCol');
    });

    it('edge_directed_endpoints_source_arrow', () => {
      _id = 800n;
      const g = createTestGraph();
      const table1 = addTestNode(g, 100, 100, 120, 200);
      const table2 = addTestNode(g, 400, 100, 120, 200);
      const e = g.Connect(table1, table2);
      e.FromTableColumnIndex = 0;
      e.ToTableColumnIndex = 2;
      e.SourceArrowhead = 'arrow';

      const [from, to, directed] = e.DirectedEndpoints();
      const largeArrow = e.HasLargeArrowheadLabel();

      const exp = reference.layoutgraphAccessors.find(s => s.name === 'edge_directed_endpoints_source_arrow');
      assert.equal(directed, exp.isDirected, 'isDirected');
      assert.equal(largeArrow, exp.largeArrowhead, 'largeArrowhead');
      // source arrow reverses: from=table2 (To), to=table1 (From)
      assert.equal(from, table2, 'directedFrom should be table2');
      assert.equal(to, table1, 'directedTo should be table1');
    });
  });

  // ── 2. Compass helpers ───────────────────────────────────────────────────────

  describe('2. Compass helpers', () => {
    for (const s of reference.compass.filter(c => c.operation === 'directionCompass')) {
      it(s.name, () => {
        assert.equal(directionCompass(s.arg1), s.result);
      });
    }

    for (const s of reference.compass.filter(c => c.operation === 'compassDelta')) {
      it(s.name, () => {
        assert.equal(compassDelta(s.arg1, s.arg2 ?? 0), s.result);
      });
    }

    for (const s of reference.compass.filter(c => c.operation === 'compassAxisDelta')) {
      it(s.name, () => {
        assert.equal(compassAxisDelta(s.arg1, s.arg2 ?? 0), s.result);
      });
    }
  });

  // ── 3. Geometry helpers ──────────────────────────────────────────────────────

  describe('3. Geometry helpers', () => {
    it('placement_distance_no_sizes', () => {
      _id = 1000n;
      const g = createTestGraph();
      const n1 = addTestNode(g, 100, 100, 60, 40);
      const n2 = addTestNode(g, 250, 180, 80, 50);
      const exp = reference.geometry.find(s => s.name === 'placement_distance_no_sizes');
      assert.equal(placementDistance(n1, n2, false), exp.value);
    });

    it('placement_distance_with_sizes', () => {
      _id = 1100n;
      const g = createTestGraph();
      const n1 = addTestNode(g, 100, 100, 60, 40);
      const n2 = addTestNode(g, 250, 180, 80, 50);
      const exp = reference.geometry.find(s => s.name === 'placement_distance_with_sizes');
      assert.ok(Math.abs(placementDistance(n1, n2, true) - exp.value) < 1e-9,
        `want ${exp.value} got ${placementDistance(n1, n2, true)}`);
    });

    it('distance_to_point_no_sizes', () => {
      _id = 1200n;
      const g = createTestGraph();
      const n1 = addTestNode(g, 100, 100, 60, 40);
      const exp = reference.geometry.find(s => s.name === 'distance_to_point_no_sizes');
      assert.ok(Math.abs(distanceToPoint(n1, new Point(200, 150), false) - exp.value) < 1e-9);
    });

    it('distance_to_point_with_sizes', () => {
      _id = 1300n;
      const g = createTestGraph();
      const n1 = addTestNode(g, 100, 100, 60, 40);
      const exp = reference.geometry.find(s => s.name === 'distance_to_point_with_sizes');
      assert.ok(Math.abs(distanceToPoint(n1, new Point(200, 150), true) - exp.value) < 1e-9);
    });

    it('sizeless_orientation', () => {
      _id = 1400n;
      const g = createTestGraph();
      const n1 = addTestNode(g, 100, 100, 60, 40);
      const n2 = addTestNode(g, 250, 180, 80, 50);
      const o = sizelessOrientation(n1, n2);
      const exp = reference.geometry.find(s => s.name === 'sizeless_orientation');
      assert.equal(Number(o), exp.orientationValue ?? 0);
    });

    it('depth_nil', () => {
      const exp = reference.geometry.find(s => s.name === 'depth_nil');
      assert.equal(depth(null), exp.depthValue);
    });

    it('depth_root', () => {
      _id = 1500n;
      const g = createTestGraph();
      const c1 = addTestNode(g, 0, 0, 10, 10);
      c1.isContainer = true;
      const exp = reference.geometry.find(s => s.name === 'depth_root');
      assert.equal(depth(c1), exp.depthValue);
    });

    it('depth_nested', () => {
      _id = 1600n;
      const g = createTestGraph();
      const c1 = addTestNode(g, 0, 0, 10, 10);
      c1.isContainer = true;
      const c2 = addTestNode(g, 0, 0, 10, 10);
      c2.isContainer = true;
      c2.Container = c1;
      const child = addTestNode(g, 0, 0, 10, 10);
      child.Container = c2;
      const exp = reference.geometry.find(s => s.name === 'depth_nested');
      assert.equal(depth(child), exp.depthValue);
    });
  });

  // ── 4. AxisScore ─────────────────────────────────────────────────────────────

  describe('4. axisScore', () => {
    it('zero_nodes', () => {
      const exp = reference.axisScore.find(s => s.name === 'zero_nodes');
      assert.equal(axisScore(null), exp.score);
      assert.equal(axisScore([]), exp.score);
    });

    it('one_node', () => {
      _id = 2000n;
      const g = createTestGraph();
      const n1 = addTestNode(g, 0, 0, 100, 50);
      const exp = reference.axisScore.find(s => s.name === 'one_node');
      assert.equal(axisScore([n1]), exp.score);
    });

    it('two_horizontal', () => {
      _id = 2100n;
      const g = createTestGraph();
      const n1 = addTestNode(g, 0, 0, 100, 50);
      const n2 = addTestNode(g, 200, 0, 100, 50);
      const exp = reference.axisScore.find(s => s.name === 'two_horizontal');
      assert.equal(axisScore([n1, n2]), exp.score);
    });

    it('two_vertical', () => {
      _id = 2200n;
      const g = createTestGraph();
      const n1 = addTestNode(g, 0, 0, 100, 50);
      const n3 = addTestNode(g, 0, 200, 100, 50);
      const exp = reference.axisScore.find(s => s.name === 'two_vertical');
      assert.equal(axisScore([n1, n3]), exp.score);
    });

    it('two_diagonal', () => {
      _id = 2300n;
      const g = createTestGraph();
      const n1 = addTestNode(g, 0, 0, 100, 50);
      const n4 = addTestNode(g, 200, 200, 100, 50);
      const exp = reference.axisScore.find(s => s.name === 'two_diagonal');
      assert.equal(axisScore([n1, n4]), exp.score);
    });

    it('three_perfect_vertical_aligned', () => {
      _id = 2400n;
      const g = createTestGraph();
      const na = addTestNode(g, 0, 100, 80, 100);
      const nb = addTestNode(g, 120, 100, 80, 100);
      const nc = addTestNode(g, 240, 100, 80, 100);
      const exp = reference.axisScore.find(s => s.name === 'three_perfect_vertical_aligned');
      assert.equal(axisScore([na, nb, nc]), exp.score);
    });

    it('ties_largest_size', () => {
      _id = 2500n;
      const g = createTestGraph();
      const nT1 = addTestNode(g, 0, 0, 100, 100);
      const nT2 = addTestNode(g, 150, 10, 100, 100);
      const nT3 = addTestNode(g, 300, 20, 80, 80);
      const exp = reference.axisScore.find(s => s.name === 'ties_largest_size');
      assert.equal(axisScore([nT1, nT2, nT3]), exp.score);
    });

    it('small_node_multipliers', () => {
      _id = 2600n;
      const g = createTestGraph();
      const ns1 = addTestNode(g, 0, 100, 100, 200);
      const ns2 = addTestNode(g, 150, 100, 50, 40);
      const ns3 = addTestNode(g, 300, 100, 50, 120);
      const score = axisScore([ns1, ns2, ns3]);
      const exp = reference.axisScore.find(s => s.name === 'small_node_multipliers');
      assert.ok(Math.abs(score - exp.score) < 1e-9, `want ${exp.score} got ${score}`);
    });
  });

  // ── 5. clusterExactlyTwoExternalConnectedNodes ───────────────────────────────

  describe('5. clusterExactlyTwoExternalConnectedNodes', () => {
    it('zero_external', () => {
      _id = 3000n;
      const g = createTestGraph();
      const cn1 = addTestNode(g, 100, 100, 50, 50);
      const cn2 = addTestNode(g, 200, 100, 50, 50);
      const cl = new Cluster({ Nodes: [cn1, cn2] });
      const [, , exact] = clusterExactlyTwoExternalConnectedNodes(cl);
      const exp = reference.clusterExternalPair.find(s => s.name === 'zero_external');
      assert.equal(exact, exp.exactlyTwo);
    });

    it('one_external', () => {
      _id = 3100n;
      const g = createTestGraph();
      const cn1 = addTestNode(g, 100, 100, 50, 50);
      const cn2 = addTestNode(g, 200, 100, 50, 50);
      const ext1 = addTestNode(g, 50, 100, 40, 40);
      const cl = new Cluster({ Nodes: [cn1, cn2] });
      cn1.Cluster = cl;
      cn2.Cluster = cl;
      cl.EdgeAbductions = [
        new EdgeAbduction({ CurrentFrom: ext1, CurrentTo: cn1, OriginallyFrom: null, OriginallyTo: cn1 }),
      ];
      const [f, , exact] = clusterExactlyTwoExternalConnectedNodes(cl);
      const exp = reference.clusterExternalPair.find(s => s.name === 'one_external');
      assert.equal(exact, exp.exactlyTwo);
      assert.notEqual(f, null);
    });

    it('two_external', () => {
      _id = 3200n;
      const g = createTestGraph();
      const cn1 = addTestNode(g, 100, 100, 50, 50);
      const cn2 = addTestNode(g, 200, 100, 50, 50);
      const ext1 = addTestNode(g, 50, 100, 40, 40);
      const ext2 = addTestNode(g, 300, 100, 40, 40);
      const cl = new Cluster({ Nodes: [cn1, cn2] });
      cn1.Cluster = cl;
      cn2.Cluster = cl;
      cl.EdgeAbductions = [
        new EdgeAbduction({ CurrentFrom: ext1, CurrentTo: cn1, OriginallyFrom: null, OriginallyTo: cn1 }),
        new EdgeAbduction({ CurrentFrom: cn2, CurrentTo: ext2, OriginallyFrom: cn2, OriginallyTo: null }),
      ];
      const [f, s, exact] = clusterExactlyTwoExternalConnectedNodes(cl);
      const exp = reference.clusterExternalPair.find(sc => sc.name === 'two_external');
      assert.equal(exact, exp.exactlyTwo);
      assert.notEqual(f, null);
      assert.notEqual(s, null);
    });

    it('three_external', () => {
      _id = 3300n;
      const g = createTestGraph();
      const cn1 = addTestNode(g, 100, 100, 50, 50);
      const cn2 = addTestNode(g, 200, 100, 50, 50);
      const ext1 = addTestNode(g, 50, 100, 40, 40);
      const ext2 = addTestNode(g, 300, 100, 40, 40);
      const ext3 = addTestNode(g, 400, 100, 40, 40);
      const cl = new Cluster({ Nodes: [cn1, cn2] });
      cn1.Cluster = cl;
      cn2.Cluster = cl;
      cl.EdgeAbductions = [
        new EdgeAbduction({ CurrentFrom: ext1, CurrentTo: cn1, OriginallyFrom: null, OriginallyTo: cn1 }),
        new EdgeAbduction({ CurrentFrom: cn2, CurrentTo: ext2, OriginallyFrom: cn2, OriginallyTo: null }),
        new EdgeAbduction({ CurrentFrom: cn2, CurrentTo: ext3, OriginallyFrom: cn2, OriginallyTo: null }),
      ];
      const [f, s, exact] = clusterExactlyTwoExternalConnectedNodes(cl);
      const exp = reference.clusterExternalPair.find(sc => sc.name === 'three_external');
      assert.equal(exact, exp.exactlyTwo);
      assert.notEqual(f, null);
      assert.notEqual(s, null);
    });
  });

  // ── 6. ObstructionBounds ────────────────────────────────────────────────────

  describe('6. ObstructionBounds / scoringNodeBounds', () => {
    it('scoring_bounds_normal', () => {
      _id = 4000n;
      const g = createTestGraph();
      const n1 = addTestNode(g, 50, 60, 100, 80);
      const b = scoringNodeBounds(n1);
      const exp = reference.obstructionBounds.find(s => s.name === 'scoring_bounds_normal');
      assert.equal(b.usable, exp.usable);
      assert.equal(b.left, exp.left);
      assert.equal(b.top, exp.top);
      assert.equal(b.right, exp.right);
      assert.equal(b.bottom, exp.bottom);
    });

    it('including_bounds', () => {
      _id = 4100n;
      const g = createTestGraph();
      const n1 = addTestNode(g, 50, 60, 100, 80);
      const n2 = addTestNode(g, 200, 150, 50, 40);
      const combined = scoringNodeBounds(n1).including(scoringNodeBounds(n2));
      const exp = reference.obstructionBounds.find(s => s.name === 'including_bounds');
      assert.equal(combined.usable, exp.usable);
      assert.equal(combined.left, exp.left);
      assert.equal(combined.top, exp.top);
      assert.equal(combined.right, exp.right);
      assert.equal(combined.bottom, exp.bottom);
    });

    it('excludes_check', () => {
      _id = 4200n;
      const g = createTestGraph();
      const n1 = addTestNode(g, 50, 60, 100, 80);
      const n2 = addTestNode(g, 200, 150, 50, 40);
      const nInside = addTestNode(g, 100, 100, 20, 20);
      const nOutside = addTestNode(g, 500, 500, 20, 20);
      const combined = scoringNodeBounds(n1).including(scoringNodeBounds(n2));
      const exp = reference.obstructionBounds.find(s => s.name === 'excludes_check');
      // exp.excludes = ['false', 'true']
      assert.equal(combined.excludes(nInside), exp.excludes[0] === 'true');
      assert.equal(combined.excludes(nOutside), exp.excludes[1] === 'true');
    });
  });

  // ── 7. flowContinuityCost ────────────────────────────────────────────────────

  describe('7. flowContinuityCost', () => {
    it('degree_zero', () => {
      _id = 5000n;
      const g = createTestGraph();
      const n0 = addTestNode(g, 100, 100, 40, 40);
      const cost = flowContinuityCost(n0, {});
      const exp = reference.flowContinuity.find(s => s.name === 'degree_zero');
      assert.equal(cost, exp.cost);
    });

    it('straight_flow', () => {
      _id = 5100n;
      const g = createTestGraph();
      const nStraight = addTestNode(g, 100, 100, 40, 40);
      const leftNode = addTestNode(g, 20, 100, 40, 40);
      const rightNode = addTestNode(g, 180, 100, 40, 40);
      const eIn = g.Connect(leftNode, nStraight);
      eIn.TargetArrowhead = 'arrow';
      const eOut = g.Connect(nStraight, rightNode);
      eOut.TargetArrowhead = 'arrow';
      const s = { nRepl: [nStraight, nStraight], aRepl: [leftNode, rightNode] };
      const cost = flowContinuityCost(nStraight, s);
      const exp = reference.flowContinuity.find(sc => sc.name === 'straight_flow');
      assert.equal(cost, exp.cost);
    });

    it('turn_flow', () => {
      _id = 5200n;
      const g = createTestGraph();
      const nTurn = addTestNode(g, 100, 100, 40, 40);
      const leftNode = addTestNode(g, 20, 100, 40, 40);
      const bottomNode = addTestNode(g, 100, 180, 40, 40);
      const eIn = g.Connect(leftNode, nTurn);
      eIn.TargetArrowhead = 'arrow';
      const eOut = g.Connect(nTurn, bottomNode);
      eOut.TargetArrowhead = 'arrow';
      const s = { nRepl: [nTurn, nTurn], aRepl: [leftNode, bottomNode] };
      const cost = flowContinuityCost(nTurn, s);
      const exp = reference.flowContinuity.find(sc => sc.name === 'turn_flow');
      assert.equal(cost, exp.cost, `want ${exp.cost} got ${cost}`);
    });

    it('reciprocal_pair', () => {
      _id = 5300n;
      const g = createTestGraph();
      const nRecip = addTestNode(g, 100, 100, 40, 40);
      const rightNode = addTestNode(g, 180, 100, 40, 40);
      const eFwd = g.Connect(nRecip, rightNode);
      eFwd.TargetArrowhead = 'arrow';
      const eBack = g.Connect(rightNode, nRecip);
      eBack.TargetArrowhead = 'arrow';
      const s = { nRepl: [nRecip, nRecip], aRepl: [rightNode, rightNode] };
      const cost = flowContinuityCost(nRecip, s);
      const exp = reference.flowContinuity.find(sc => sc.name === 'reciprocal_pair');
      assert.equal(cost, exp.cost);
    });
  });

  // ── 8. Symmetry ──────────────────────────────────────────────────────────────

  describe('8. NodeSymmetry / ColumnCrossingCost', () => {
    it('perfect_pair_symmetry', () => {
      _id = 6000n;
      const g = createTestGraph();
      const center = addTestNode(g, 200, 200, 60, 60);
      const left = addTestNode(g, 80, 200, 60, 60);
      const right = addTestNode(g, 320, 200, 60, 60);
      g.Connect(center, left);
      g.Connect(center, right);
      const symm = NodeSymmetry(NULL_CTX, center, null);
      const exp = reference.symmetry.find(s => s.name === 'perfect_pair_symmetry');
      assert.equal(symm, exp.symmetry);
    });

    it('single_neighbor_symmetry', () => {
      _id = 6100n;
      const g = createTestGraph();
      const cSingle = addTestNode(g, 200, 200, 60, 60);
      const lSingle = addTestNode(g, 80, 200, 60, 60);
      g.Connect(cSingle, lSingle);
      const symm = NodeSymmetry(NULL_CTX, cSingle, null);
      const exp = reference.symmetry.find(s => s.name === 'single_neighbor_symmetry');
      assert.equal(symm, exp.symmetry);
    });

    it('table_column_crossing_cost', () => {
      _id = 6200n;
      const g = createTestGraph();
      const t1 = addTestNode(g, 100, 100, 100, 150);
      t1.SetShape('Table');
      t1.SetNumColumns(4);
      const t2 = addTestNode(g, 300, 100, 100, 150);
      t2.SetShape('Table');
      t2.SetNumColumns(4);
      const eCross1 = g.Connect(t1, t2);
      eCross1.FromTableColumnIndex = 0;
      eCross1.ToTableColumnIndex = 2;
      const eCross2 = g.Connect(t1, t2);
      eCross2.FromTableColumnIndex = 1;
      eCross2.ToTableColumnIndex = 0;
      const crossCost = ColumnCrossingCost(NULL_CTX, t1, null);
      const exp = reference.symmetry.find(s => s.name === 'table_column_crossing_cost');
      assert.ok(Math.abs(crossCost - exp.crossingCost) < 1e-9,
        `want ${exp.crossingCost} got ${crossCost}`);
    });
  });

  // ── 9. NodeEdgeLength ────────────────────────────────────────────────────────

  describe('9. NodeEdgeLength', () => {
    const elCases = [
      { name: 'horizontal_edge_sizeless_default', sizes: false, gap: false, dir: false },
      { name: 'horizontal_edge_sizeless_dir',     sizes: false, gap: false, dir: true  },
      { name: 'horizontal_edge_sized_default',    sizes: true,  gap: false, dir: false },
      { name: 'horizontal_edge_sized_gap',        sizes: true,  gap: true,  dir: false },
      { name: 'horizontal_edge_sized_dir',        sizes: true,  gap: false, dir: true  },
      { name: 'horizontal_edge_sized_gap_dir',    sizes: true,  gap: true,  dir: true  },
    ];

    for (const c of elCases) {
      it(c.name, () => {
        _id = 7000n;
        const g = createTestGraph();
        const src = addTestNode(g, 100, 100, 80, 50);
        const tgt = addTestNode(g, 300, 100, 80, 50);
        const e = g.Connect(src, tgt);
        e.TargetArrowhead = 'arrow';
        const score = NodeEdgeLength(NULL_CTX, src,
          new EdgeLengthOptions({ IncludeNodeSizes: c.sizes, EnforceMinimumGap: c.gap, PenalizeDirection: c.dir }));
        const exp = reference.nodeEdgeLength.find(s => s.name === c.name);
        assert.ok(Math.abs(score - exp.score) < 1e-9, `want ${exp.score} got ${score}`);
      });
    }

    it('three_parallel_edges', () => {
      _id = 7100n;
      const g = createTestGraph();
      const pSrc = addTestNode(g, 100, 100, 60, 40);
      const pTgt = addTestNode(g, 250, 100, 60, 40);
      g.Connect(pSrc, pTgt);
      g.Connect(pSrc, pTgt);
      g.Connect(pSrc, pTgt);
      const score = NodeEdgeLength(NULL_CTX, pSrc, new EdgeLengthOptions({ IncludeNodeSizes: true }));
      const exp = reference.nodeEdgeLength.find(s => s.name === 'three_parallel_edges');
      assert.ok(Math.abs(score - exp.score) < 1e-9, `want ${exp.score} got ${score}`);
    });

    it('common_uncle_siblings_axis_penalty', () => {
      _id = 7200n;
      const g = createTestGraph();
      const u1 = addTestNode(g, 100, 100, 50, 50);
      const u2 = addTestNode(g, 200, 200, 50, 50);
      g.CommonUncleSiblings = new Map();
      g.CommonUncleSiblings.set(u1, [u1, u2]);
      const score = NodeEdgeLength(NULL_CTX, u1, new EdgeLengthOptions({ IncludeNodeSizes: false }));
      const exp = reference.nodeEdgeLength.find(s => s.name === 'common_uncle_siblings_axis_penalty');
      assert.equal(score, exp.score);
    });
  });

  // ── 10. NodeEdgeLengthScorer ─────────────────────────────────────────────────

  describe('10. NodeEdgeLengthScorer', () => {
    it('live_geometry_mutation', () => {
      _id = 8000n;
      const g = createTestGraph();
      const src = addTestNode(g, 100, 100, 60, 40);
      const tgt = addTestNode(g, 250, 100, 60, 40);
      g.Connect(src, tgt);
      const opts = new EdgeLengthOptions({ IncludeNodeSizes: true, PenalizeDirection: true });
      const scorer = NewNodeEdgeLengthScorer(src, opts);
      const s1 = scorer.Score(NULL_CTX);

      // Mutate live geometry — tgt.TopLeft.X = 350
      tgt.TopLeft = new Point(350, 100);
      const s2 = scorer.Score(NULL_CTX);

      scorer.Close();
      let closedErr = null;
      try { scorer.Score(NULL_CTX); } catch (e) { closedErr = e.message; }

      const exp = reference.nodeEdgeLengthScorer.find(s => s.name === 'live_geometry_mutation');
      assert.ok(Math.abs(s1 - exp.score1) < 1e-9, `score1 want ${exp.score1} got ${s1}`);
      assert.ok(Math.abs(s2 - exp.score2) < 1e-9, `score2 want ${exp.score2} got ${s2}`);
      assert.equal(closedErr, exp.closedScoreError);
    });
  });

  // ── 11. Cancellation ─────────────────────────────────────────────────────────

  describe('11. Cancellation', () => {
    it('immediate_entry_cancellation', () => {
      _id = 9000n;
      const g = createTestGraph();
      const src = addTestNode(g, 100, 100, 80, 50);
      const tgt = addTestNode(g, 300, 100, 80, 50);
      const e = g.Connect(src, tgt);
      e.TargetArrowhead = 'arrow';
      const canceledCtx = { Err() { return new Error('context canceled'); } };
      let caught = null;
      try { NodeEdgeLength(canceledCtx, src, new EdgeLengthOptions()); } catch (e2) { caught = e2.message; }
      const exp = reference.cancellation.find(s => s.name === 'immediate_entry_cancellation');
      assert.equal(caught, exp.expectedError);
    });

    it('counting_context_cancellation', () => {
      _id = 9100n;
      const g = createTestGraph();
      const src = addTestNode(g, 100, 100, 80, 50);
      const tgt = addTestNode(g, 300, 100, 80, 50);
      const e = g.Connect(src, tgt);
      e.TargetArrowhead = 'arrow';
      const exp = reference.cancellation.find(s => s.name === 'counting_context_cancellation');
      const ctx = new CountingContext(exp.cancelAt);
      let caught = null;
      try { NodeEdgeLength(ctx, src, new EdgeLengthOptions()); } catch (e2) { caught = e2.message; }
      assert.equal(caught, exp.expectedError);
      assert.equal(ctx.count, exp.checkCount);
    });
  });
});

