// Slice 47 — Search and edge router real-Go oracle replay.
// Fixture: go-slice47-search-reference.json, generated by
// internal/routing/go_slice47_search_oracle_test.go (TALA_SLICE47_ORACLE=1).

import { describe, it as bunIt, expect } from 'bun:test';
import { readFileSync } from 'node:fs';

import { Graph } from '../../src/graph/graph.js';
import { Node } from '../../src/graph/node.js';
import { Cluster, ClusterArrangement } from '../../src/graph/cluster.js';
import { Point } from '../../src/geometry/point.js';
import { backgroundWorkContext } from '../../src/limits/work-context.js';
import { defaultOVGBuildLimits, newOVGBuildGuard } from '../../src/routing/ovg-resource.js';
import { buildOVGFromGraphWithGuard } from '../../src/routing/ovg.js';
import {
  newOVGEdgeRouterWithWorkLimit,
  RouteGenerationFlavor,
} from '../../src/routing/ovg-edge-router.js';
import { PriorityQueue } from '../../src/routing/priority-queue.js';
import { NewOVGNode } from '../../src/routing/ovg-node.js';
import { MAX_ROUTE_SEARCH_WORK_UNITS } from '../../src/routing/route-guards.js';

const it = (name, fn) => bunIt(name, fn, 600_000);

const fixture = JSON.parse(
  readFileSync(new URL('../fixtures/go-slice47-search-reference.json', import.meta.url), 'utf8'),
);
const bg = backgroundWorkContext();

function parseF(val) {
  if (val === 'NaN') return NaN;
  if (val === '+Inf') return Infinity;
  if (val === '-Inf') return -Infinity;
  if (val === '-0') return -0;
  return typeof val === 'number' ? val : parseFloat(val);
}

function createNode(ns) {
  const n = new Node(BigInt(ns.id), parseF(ns.w), parseF(ns.h));
  n.TopLeft = new Point(parseF(ns.x), parseF(ns.y));
  if (ns.shape) n.SetShape(ns.shape);
  if (ns.columns) n.SetNumColumns(ns.columns);
  return n;
}

function buildGraph(spec) {
  const g = new Graph();
  const nodeMap = new Map();

  for (const ns of spec.nodes ?? []) {
    const n = createNode(ns);
    g.AddNode(n);
    nodeMap.set(ns.id, n);
  }

  for (const ns of spec.nodes ?? []) {
    if (ns.container) {
      const parent = nodeMap.get(ns.container);
      if (parent) {
        nodeMap.get(ns.id).Container = parent;
      }
    }
  }

  for (const cs of spec.clusters ?? []) {
    const vessel = createNode(cs.vessel);
    const c = new Cluster({ Vessel: vessel });
    for (const nid of cs.nodes ?? []) {
      const n = nodeMap.get(nid);
      if (n) {
        c.Nodes.push(n);
        n.Cluster = c;
      }
    }
    if (cs.arrangement === 'Column') {
      c.Arrangement = ClusterArrangement.Column;
      c.DesiredArrangement = ClusterArrangement.Column;
    } else {
      c.Arrangement = ClusterArrangement.Row;
      c.DesiredArrangement = ClusterArrangement.Row;
    }
    g.Clusters.set(vessel, c);
  }

  const edges = [];
  for (const es of spec.edges ?? []) {
    const fromNode = nodeMap.get(es.from);
    const toNode = nodeMap.get(es.to);
    const e = g.Connect(fromNode, toNode);
    if (es.from_col != null) {
      e.FromTableColumnIndex = es.from_col;
    }
    if (es.to_col != null) {
      e.ToTableColumnIndex = es.to_col;
    }
    if (es.src_arrow) {
      e.SourceArrowhead = 'triangle';
    }
    if (es.tgt_arrow) {
      e.TargetArrowhead = 'triangle';
    }
    if (es.src_label) {
      e.SourceArrowheadLabel = { Text: es.src_label };
    }
    if (es.tgt_label) {
      e.TargetArrowheadLabel = { Text: es.tgt_label };
    }
    if (es.label) {
      e.Label = { Text: es.label };
    }
    edges.push(e);
  }

  return { g, edges, nodeMap };
}

describe('Slice 47 Search & Router Oracle (Real Go)', () => {
  it('covers all required scenarios', () => {
    expect(fixture.cases.length).toBeGreaterThanOrEqual(14);
    expect(fixture.results.length).toBe(fixture.cases.length);
  });

  for (let i = 0; i < fixture.cases.length; i++) {
    const caseSpec = fixture.cases[i];
    const expected = fixture.results[i];

    it(`route scenario: ${caseSpec.name}`, () => {
      const { g, edges } = buildGraph(caseSpec);

      const limits = defaultOVGBuildLimits();
      const guard = newOVGBuildGuard(bg, limits);
      const ovg = buildOVGFromGraphWithGuard(g, null, guard);

      let flavor = RouteGenerationFlavor.ShortestToLongest;
      if (caseSpec.flavor === 'LongestToShortest') {
        flavor = RouteGenerationFlavor.LongestToShortest;
      } else if (caseSpec.flavor === 'TopDownLeftRight') {
        flavor = RouteGenerationFlavor.TopDownLeftRight;
      }

      const router = newOVGEdgeRouterWithWorkLimit(
        bg,
        flavor,
        ovg,
        g,
        null,
        edges,
        MAX_ROUTE_SEARCH_WORK_UNITS
      );

      const resp = router.generateRoutes(bg, caseSpec.straight_line_fallback);

      if (!expected.success) {
        expect(resp.Err).not.toBeNull();
        return;
      }

      expect(resp.Err).toBeNull();
      const expectedDist = parseF(expected.total_distance);
      expect(Math.abs(resp.Distance - expectedDist)).toBeLessThan(0.001);

      expect(resp.Routes.length).toBe(expected.routes.length);

      for (let rIdx = 0; rIdx < expected.routes.length; rIdx++) {
        const expRoute = expected.routes[rIdx];
        const actualRoute = resp.Routes[rIdx];

        expect(actualRoute.OVGNodes.length).toBe(expRoute.points.length);
        for (let pIdx = 0; pIdx < expRoute.points.length; pIdx++) {
          const expPt = expRoute.points[pIdx];
          const actPt = actualRoute.OVGNodes[pIdx].Point;
          expect(Math.abs(actPt.X - parseF(expPt.x))).toBeLessThan(0.001);
          expect(Math.abs(actPt.Y - parseF(expPt.y))).toBeLessThan(0.001);
        }

        expect(Math.abs(actualRoute.FromPort.X - parseF(expRoute.from_port.x))).toBeLessThan(0.001);
        expect(Math.abs(actualRoute.FromPort.Y - parseF(expRoute.from_port.y))).toBeLessThan(0.001);
        expect(Math.abs(actualRoute.ToPort.X - parseF(expRoute.to_port.x))).toBeLessThan(0.001);
        expect(Math.abs(actualRoute.ToPort.Y - parseF(expRoute.to_port.y))).toBeLessThan(0.001);
      }
    });
  }

  describe('Priority Queue Oracle', () => {
    for (const pqCase of fixture.pq_results ?? []) {
      it(`pq parity: ${pqCase.name}`, () => {
        const pq = new PriorityQueue();

        if (pqCase.name === 'equal-priorities-order') {
          const nodes = [
            NewOVGNode(new Point(0, 0)),
            NewOVGNode(new Point(1, 1)),
            NewOVGNode(new Point(2, 2)),
            NewOVGNode(new Point(3, 3)),
          ];
          nodes.forEach((n, idx) => { n.Index = idx; });

          pq.push(10.0, nodes[0], true, null);
          pq.push(10.0, nodes[1], false, null);
          pq.push(10.0, nodes[2], true, null);
          pq.push(10.0, nodes[3], false, null);

          const pops = [];
          while (!pq.empty()) {
            const entry = pq.pop(null);
            pops.push({
              priority: entry.priority,
              is_horiz: entry.isHorizontal,
              node_id: entry.node.Index,
            });
          }

          expect(pops.length).toBe(pqCase.pops.length);
          for (let i = 0; i < pops.length; i++) {
            expect(pops[i].priority).toBe(parseF(pqCase.pops[i].priority));
            expect(pops[i].is_horiz).toBe(pqCase.pops[i].is_horiz);
            expect(pops[i].node_id).toBe(pqCase.pops[i].node_id);
          }
        } else if (pqCase.name === 'decrease-key-order') {
          const nodes = Array.from({ length: 5 }, (_, i) => {
            const n = NewOVGNode(new Point(i, i));
            n.Index = i;
            return n;
          });

          const e0 = pq.push(50.0, nodes[0], true, null);
          const e1 = pq.push(40.0, nodes[1], false, null);
          const e2 = pq.push(30.0, nodes[2], true, null);
          const e3 = pq.push(20.0, nodes[3], false, null);
          const e4 = pq.push(10.0, nodes[4], true, null);

          pq.decrease(e0, 5.0, null);
          pq.decrease(e1, 15.0, null);
          pq.decrease(e2, 2.0, null);

          const pops = [];
          while (!pq.empty()) {
            const entry = pq.pop(null);
            pops.push({
              priority: entry.priority,
              is_horiz: entry.isHorizontal,
              node_id: entry.node.Index,
            });
          }

          expect(pops.length).toBe(pqCase.pops.length);
          for (let i = 0; i < pops.length; i++) {
            expect(pops[i].priority).toBe(parseF(pqCase.pops[i].priority));
            expect(pops[i].is_horiz).toBe(pqCase.pops[i].is_horiz);
            expect(pops[i].node_id).toBe(pqCase.pops[i].node_id);
          }
        } else if (pqCase.name === 'large-queue-mixed') {
          const nodes = Array.from({ length: 100 }, (_, i) => {
            const n = NewOVGNode(new Point(i, i));
            n.Index = i;
            return n;
          });

          const entries = [];
          for (let i = 0; i < 100; i++) {
            const p = ((i * 37) % 100) + 1.0;
            entries.push(pq.push(p, nodes[i], i % 2 === 0, null));
          }

          for (let i = 10; i < 90; i += 5) {
            try {
              pq.decrease(entries[i], i / 10.0, null);
            } catch {}
          }

          const pops = [];
          while (!pq.empty()) {
            const entry = pq.pop(null);
            pops.push({
              priority: entry.priority,
              is_horiz: entry.isHorizontal,
              node_id: entry.node.Index,
            });
          }

          expect(pops.length).toBe(pqCase.pops.length);
          for (let i = 0; i < pops.length; i++) {
            expect(pops[i].priority).toBe(parseF(pqCase.pops[i].priority));
            expect(pops[i].is_horiz).toBe(pqCase.pops[i].is_horiz);
            expect(pops[i].node_id).toBe(pqCase.pops[i].node_id);
          }
        }
      });
    }
  });
});
