// Slice 47 — OVG substrate real-Go oracle replay.
// Fixture: go-slice47-ovg-reference.json, generated by
// internal/routing/go_slice47_ovg_oracle_test.go (TALA_SLICE47_ORACLE=1).
//
// Every scenario is rebuilt from its portable spec, the OVG is built by the JS
// port and dumped canonically exactly like the Go generator (nodes sorted by
// X, Y, role key; everything else by canonical index; edge order kept), and
// the resource/cancellation probes recorded by Go are replayed.
import { describe, it as bunIt, expect } from 'bun:test';
import { readFileSync } from 'node:fs';

import { Graph } from '../../src/graph/graph.js';
import { Node } from '../../src/graph/node.js';
import { Cluster } from '../../src/graph/cluster.js';
import { Sequence } from '../../src/graph/sequence.js';
import { Hierarchy } from '../../src/graph/hierarchy.js';
import { Point } from '../../src/geometry/point.js';
import { backgroundWorkContext } from '../../src/limits/work-context.js';
import { preprocess as preprocessTrees, place as placeTrees } from '../../src/trees/index.js';
import { contextWithRouteAggregateWork, newRouteWorkGuard } from '../../src/routing/route-guards.js';
import { OVGBuildLimits, defaultOVGBuildLimits, newOVGBuildGuard } from '../../src/routing/ovg-resource.js';
import { buildOVGFromGraphWithGuard } from '../../src/routing/ovg.js';
import { newOVGForHierarchy } from '../../src/routing/ovg-hierarchy.js';

const it = (name, fn) => bunIt(name, fn, 600_000);

const fixture = JSON.parse(
  readFileSync(new URL('../fixtures/go-slice47-ovg-reference.json', import.meta.url), 'utf8'),
);
const bg = backgroundWorkContext();

// ── Builders (mirror s47Spec.build / run) ────────────────────────────────────

function newNode(ns) {
  const n = new Node(BigInt(ns.id), ns.w, ns.h);
  if (ns.shape) n.SetShape(ns.shape);
  if (ns.columns) n.SetNumColumns(ns.columns);
  n.TopLeft = new Point(ns.x, ns.y);
  n.IsInvisible = Boolean(ns.invisible);
  if (ns.fixed) n.FixedTopLeft = n.TopLeft.copy();
  return n;
}

function build(spec) {
  const g = new Graph();
  const nodes = new Map();
  const order = [];
  for (const ns of spec.nodes ?? []) {
    const n = newNode(ns);
    const container = ns.container ? nodes.get(ns.container) : null;
    g.AddNewNodeToContainer(container, n);
    nodes.set(ns.id, n);
    order.push(n);
  }
  for (const es of spec.edges ?? []) {
    const e = g.Connect(nodes.get(es.from), nodes.get(es.to));
    e.SourceArrowhead = es.src ?? '';
    e.TargetArrowhead = es.tgt ?? '';
  }
  for (const d of spec.directions ?? []) {
    g.Directions.set(d.container ? nodes.get(d.container) : null, d.orientation);
  }
  const hiers = [];
  for (const hs of spec.hierarchies ?? []) {
    const h = new Hierarchy();
    h.ReplaceLevels(new Map((hs.levels ?? []).map((l) => [nodes.get(l.id), l.level])));
    for (const l of hs.levels ?? []) nodes.get(l.id).Hierarchy = h;
    for (const id of hs.members ?? []) nodes.get(id).Hierarchy = h;
    hiers.push(h);
  }
  for (const cs of spec.clusters ?? []) {
    const cluster = new Cluster({ Vessel: newNode(cs.vessel), Nodes: [] });
    for (const id of cs.nodes) {
      cluster.Nodes.push(nodes.get(id));
      nodes.get(id).Cluster = cluster;
    }
    g.Clusters.set(cluster.Vessel, cluster);
  }
  for (const ss of spec.sequences ?? []) {
    const sequence = new Sequence({ Vessel: newNode(ss.vessel), Nodes: [] });
    for (const id of ss.nodes) {
      sequence.Nodes.push(nodes.get(id));
      nodes.get(id).Sequence = sequence;
    }
  }
  const nearby = (spec.nearby ?? []).map(newNode);
  if (spec.trees) {
    preprocessTrees(bg, g);
    placeTrees(bg, g, null);
  }
  return { g, nodes, order, nearby, hiers };
}

function run(spec, b, guard) {
  if (spec.direct === 'hierarchy') return newOVGForHierarchy(b.g, b.hiers[0], guard);
  return buildOVGFromGraphWithGuard(b.g, b.nearby, guard);
}

// ── Canonical dump (mirror s47DumpOVG) ───────────────────────────────────────

const f = (v) => {
  if (v !== v) return 'NaN';
  if (v === Infinity) return '+Inf';
  if (v === -Infinity) return '-Inf';
  return v;
};
const id = (n) => Number(n.ID);
const sortedIDs = (nodes) => nodes.map(id).sort((a, b) => a - b);

function ownersOf(node) {
  const owners = [];
  for (const [owner, metadata] of node.portOwners()) {
    owners.push([id(owner), metadata.directions, metadata.isCenterPort ? 1 : 0]);
  }
  owners.sort((a, b) => a[0] - b[0]);
  return owners;
}

function dumpOVG(ovg) {
  const centerOf = new Map();
  for (const [owner, center] of ovg.Centers) {
    if (!centerOf.has(center)) centerOf.set(center, []);
    centerOf.get(center).push(owner);
  }
  const keys = new Map();
  for (const node of ovg.Nodes) {
    const owners = ownersOf(node).map((o) => `${o[0]}:${o[1]}:${o[2]}`).join(',');
    keys.set(node, `c${node.IsNodeCenter};co${sortedIDs(centerOf.get(node) ?? []).join(',')};t${node.IsTunnel};o${owners}`);
  }
  const sorted = ovg.Nodes.slice().sort((a, b) => {
    if (a.X !== b.X) return a.X < b.X ? -1 : 1;
    if (a.Y !== b.Y) return a.Y < b.Y ? -1 : 1;
    const ka = keys.get(a);
    const kb = keys.get(b);
    return ka < kb ? -1 : (ka > kb ? 1 : 0);
  });
  const index = new Map(sorted.map((node, i) => [node, i]));
  const ref = (node) => [index.has(node) ? index.get(node) : -1, f(node.X), f(node.Y)];
  const edgeIndex = new Map();
  const edges = [];
  ovg.Edges.forEach((edge, i) => {
    edgeIndex.set(edge, i);
    edges.push([index.get(edge.From) ?? 0, index.get(edge.To) ?? 0, f(edge.Distance)]);
  });
  let indexOK = true;
  ovg.Nodes.forEach((node, i) => {
    if (node.Index !== i) indexOK = false;
  });
  const nodes = sorted.map((node) => ({
    x: f(node.X),
    y: f(node.Y),
    key: keys.get(node),
    container: node.Container == null ? 0 : id(node.Container),
    near: sortedIDs([...(node.IsNearPort ?? [])]),
    owners: ownersOf(node),
    adj: node.Edges.map((e) => {
      const adj = node.adjacent(e);
      return index.has(adj) ? index.get(adj) : -1;
    }),
  }));
  const byID = (map) => [...map.keys()].sort((a, b) => id(a) - id(b));
  const ports = byID(ovg.Ports).map((owner) => [id(owner), ovg.Ports.get(owner).map(ref)]);
  const centers = byID(ovg.Centers).map((owner) => [id(owner), ref(ovg.Centers.get(owner))]);
  const occupied = [...ovg.OccupiedPoints.entries()]
    .sort(([a], [b]) => (a.X !== b.X ? (a.X < b.X ? -1 : 1) : (a.Y < b.Y ? -1 : (a.Y > b.Y ? 1 : 0))))
    .map(([p, node]) => [f(p.X), f(p.Y), ref(node)]);
  const axis = (map) => [...map.keys()].sort((a, b) => a - b)
    .map((c) => [f(c), map.get(c).map((e) => edgeIndex.get(e))]);
  const orNull = (list) => (list.length === 0 ? null : list);
  return {
    nodes: orNull(nodes),
    edges: orNull(edges),
    ports: orNull(ports),
    centers: orNull(centers),
    occupied: orNull(occupied),
    vertical: axis(ovg.VerticalEdges),
    horizontal: axis(ovg.HorizontalEdges),
    inside: orNull((ovg.NodesInsideBoundingBox ?? []).map(id)),
    fixedCache: ovg.fixedOverlapsCache.length,
    indexOK,
  };
}

// ── Probes (mirror s47Spec.budget) ───────────────────────────────────────────

const CANCELED = new Error('context canceled');

function countingContext(cancelAt) {
  return {
    calls: 0,
    Err() {
      this.calls++;
      if (cancelAt > 0 && this.calls >= cancelAt) return CANCELED;
      return null;
    },
  };
}

const counters = (guard) => ({ candidates: guard.candidates, nodes: guard.nodes, edges: guard.edges, work: guard.work });

function limitsFor(resource, limit) {
  const limits = defaultOVGBuildLimits();
  const field = { candidates: 'intersectionCandidates', nodes: 'nodes', edges: 'edges', work: 'work' }[resource];
  return new OVGBuildLimits({ ...limits, [field]: limit });
}

/** Builds with a fresh guard; returns [error message, guard|null]. */
function attempt(spec, makeGuard) {
  const b = build(spec);
  let guard = null;
  try {
    guard = makeGuard();
    run(spec, b, guard);
    return ['', guard];
  } catch (err) {
    if (err?.goPanic !== undefined || err instanceof TypeError) throw err;
    return [err.message, guard];
  }
}

function replayBudget(spec, expected) {
  const [baseErr, base] = attempt(spec, () => newOVGBuildGuard(bg, defaultOVGBuildLimits()));
  expect(baseErr).toBe('');
  const budget = { totals: counters(base), errCalls: 0, limits: [], aggregate: [], cancel: [] };
  for (const probe of expected.limits) {
    const [error, guard] = attempt(spec, () => newOVGBuildGuard(bg, limitsFor(probe.resource, probe.limit)));
    budget.limits.push({ resource: probe.resource, limit: probe.limit, error, counters: error ? null : counters(guard) });
  }
  for (const probe of expected.aggregate) {
    const [error, guard] = attempt(spec, () => {
      const aggregate = newRouteWorkGuard(bg, 'EdgeRouting', probe.limit);
      return newOVGBuildGuard(contextWithRouteAggregateWork(bg, aggregate), defaultOVGBuildLimits());
    });
    budget.aggregate.push({ resource: 'aggregate', limit: probe.limit, error, counters: error ? null : counters(guard) });
  }
  const counting = countingContext(0);
  const [countErr] = attempt(spec, () => newOVGBuildGuard(counting, defaultOVGBuildLimits()));
  expect(countErr).toBe('');
  budget.errCalls = counting.calls;
  for (const probe of expected.cancel) {
    const ctx = countingContext(probe.at);
    const [error, guard] = attempt(spec, () => newOVGBuildGuard(ctx, defaultOVGBuildLimits()));
    budget.cancel.push({ at: probe.at, error, counters: error || guard == null ? null : counters(guard), calls: ctx.calls });
  }
  return budget;
}

function replay(scenario) {
  const { spec } = scenario;
  const b = build(spec);
  const guard = newOVGBuildGuard(bg, defaultOVGBuildLimits());
  const res = { error: '' };
  let ovg = null;
  try {
    ovg = run(spec, b, guard);
  } catch (err) {
    if (err?.goPanic) return { error: '', panic: err.message, totals: { candidates: 0, nodes: 0, edges: 0, work: 0 } };
    if (err instanceof TypeError) throw err;
    res.error = err.message;
  }
  if (ovg != null) res.ovg = dumpOVG(ovg);
  res.totals = counters(guard);
  if (!scenario.budget) res.totals.work = 0;
  if (spec.direct) {
    res.restored = b.order.map((n) => [id(n), n.TopLeft.X, n.TopLeft.Y, n.Width, n.Height].map(f));
  }
  return res;
}

describe('Slice 47 OVG oracle (real Go)', () => {
  it('covers the required scenario groups', () => {
    const names = fixture.scenarios.map((s) => s.name);
    expect(names.length).toBeGreaterThanOrEqual(20);
    expect(fixture.scenarios.filter((s) => s.budget).length).toBeGreaterThanOrEqual(6);
  });

  for (const scenario of fixture.scenarios) {
    it(`structure: ${scenario.name}`, () => {
      const expected = { ...scenario.result };
      delete expected.budget;
      expect(replay(scenario)).toEqual(expected);
    });
    if (scenario.budget) {
      it(`budget/cancellation: ${scenario.name}`, () => {
        expect(replayBudget(scenario.spec, scenario.result.budget)).toEqual(scenario.result.budget);
      });
    }
  }
});
