// Slice 50 — real-Go seed-selection oracle replay.
// Fixture: go-slice50-selection-reference.json, generated by
// d2layouts/d2talalayout/go_slice50_selection_oracle_test.go.
import { describe, it, expect } from 'bun:test';
import { readFileSync } from 'node:fs';

import { Score } from '../../src/quality/score.js';
import { WorkContext, backgroundWorkContext } from '../../src/limits/work-context.js';
import { normalizeSeeds, toInt64Seed } from '../../src/layout/options.js';
import { SeedAttempt, considerSeedCandidate, coordinateLocalSeeds, refineSeedResult } from '../../src/layout/coordinator.js';

const fixture = JSON.parse(readFileSync(new URL('../fixtures/go-slice50-selection-reference.json', import.meta.url), 'utf8'));

function num(value) {
  if (value === 'NaN') return NaN;
  if (value === '+Inf') return Infinity;
  if (value === '-Inf') return -Infinity;
  return value;
}

function score(s) {
  return new Score(num(s.penalty), num(s.area));
}

function capture(fn) {
  try {
    return { value: fn(), error: '' };
  } catch (err) {
    return { value: undefined, error: err instanceof Error ? err.message : String(err) };
  }
}

function cancellableContext() {
  let canceled = false;
  const ctx = new WorkContext({ isCancelled: () => canceled, doneAvailable: true });
  return { ctx, cancel: () => { canceled = true; } };
}

function permutations(items) {
  if (items.length <= 1) return [items];
  const out = [];
  items.forEach((item, i) => {
    for (const rest of permutations([...items.slice(0, i), ...items.slice(i + 1)])) out.push([item, ...rest]);
  });
  return out;
}

describe('Slice 50 oracle — normalizeSeeds', () => {
  for (const c of fixture.normalize) {
    it(`[${c.input.slice(0, 6).join(',')}${c.input.length > 6 ? ',…' : ''}] (${c.input.length})`, () => {
      const result = capture(() => normalizeSeeds(c.input.map((s, i) => toInt64Seed(BigInt(s), i))));
      expect(result.error).toBe(c.error);
      if (c.error === '') {
        expect(result.value.map(String)).toEqual(c.output);
      }
    });
  }
});

describe('Slice 50 oracle — score comparison', () => {
  for (const c of fixture.compare) {
    it(`${JSON.stringify(c.left)} vs ${JSON.stringify(c.right)}`, () => {
      expect(score(c.left).Compare(score(c.right))).toBe(c.compare);
    });
  }
});

describe('Slice 50 oracle — coordinateLocalSeeds', () => {
  for (const c of fixture.coordinate) {
    it(`${c.name} (concurrency ${c.concurrency}) — every completion order`, async () => {
      const seeds = c.seeds.map((s) => BigInt(s));
      for (const order of permutations(seeds.map((_, i) => i))) {
        const graphs = c.attempts.map(() => ({}));
        const { ctx, cancel } = cancellableContext();
        if (c.canceled) cancel();
        const rank = new Map(order.map((index, position) => [index, position]));
        const runs = [];
        const result = await (async () => {
          try {
            const best = await coordinateLocalSeeds(ctx, seeds, c.concurrency, (index, seed) => {
              runs.push(index);
              const attempt = new SeedAttempt(index, seed);
              const spec = c.attempts[index];
              if (spec.error) attempt.error = new Error(spec.error);
              else attempt.result = { graph: graphs[index], score: score(spec.score) };
              // Complete in the permuted order.
              return new Promise((resolve) => setTimeout(() => resolve(attempt), rank.get(index)));
            });
            return { winner: graphs.indexOf(best.graph), error: '' };
          } catch (err) {
            return { winner: -1, error: err.message };
          }
        })();
        expect(result).toEqual({ winner: c.winner, error: c.error });
        expect(runs.slice().sort()).toEqual(seeds.map((_, i) => i));
      }
    });
  }
});

describe('Slice 50 oracle — optional candidate and refinement', () => {
  for (const c of fixture.candidate) {
    it(c.name, () => {
      const { ctx, cancel } = cancellableContext();
      const incumbent = { graph: {}, score: score(c.incumbent) };
      const candidate = { graph: {}, score: score(c.candidate) };
      const canceledErr = new Error('context canceled');
      const build = () => {
        switch (c.mode) {
          case 'error':
            throw new Error('candidate failed');
          case 'panic':
            throw 'candidate panic';
          case 'canceled-error':
            throw new Error('CompoundRoutes: context canceled', { cause: canceledErr });
          case 'ok-then-cancel':
            cancel();
            return candidate;
          case 'panic-then-cancel':
            cancel();
            throw 'candidate panic';
          default:
            return candidate;
        }
      };
      const run = c.refine ? refineSeedResult : considerSeedCandidate;
      const result = capture(() => run(ctx, incumbent, build));
      expect(result.error).toBe(c.error);
      if (c.error === '') {
        expect(result.value === incumbent ? 'incumbent' : result.value === candidate ? 'candidate' : 'none').toBe(c.selected);
      } else {
        // Go returns the incumbent alongside the error; JS throws.
        expect(c.selected).toBe('incumbent');
      }
    });
  }
});

describe('Slice 50 — coordinator invariants', () => {
  it('runs every configured seed exactly once with bounded concurrency', async () => {
    const seeds = [1n, 2n, 3n, 4n, 5n];
    let inFlight = 0;
    let peak = 0;
    const seen = [];
    await coordinateLocalSeeds(backgroundWorkContext(), seeds, 2, async (index, seed) => {
      inFlight++;
      peak = Math.max(peak, inFlight);
      seen.push(seed);
      await new Promise((resolve) => setTimeout(resolve, 5 - index));
      inFlight--;
      const attempt = new SeedAttempt(index, seed);
      attempt.result = { graph: {}, score: new Score(1, 1) };
      return attempt;
    });
    expect(peak).toBeLessThanOrEqual(2);
    expect(seen.slice().sort()).toEqual(seeds);
  });
});
