// Slice 46 — structural placement real-Go oracle replay.
// Fixture: go-slice46-placement-reference.json, generated by
// internal/placement/go_slice46_structural_oracle_test.go.
import { describe, it as bunIt, expect } from 'bun:test';

// Full Place runs with cancellation probes exceed bun's 5 s default.
const it = (name, fn) => bunIt(name, fn, 300_000);
import { readFileSync } from 'node:fs';

import { Graph, newGraph } from '../../src/graph/graph.js';
import { Node } from '../../src/graph/node.js';
import { Label } from '../../src/graph/label.js';
import { Point } from '../../src/geometry/point.js';
import { Orientation } from '../../src/geometry/orientation.js';
import { copyEntitiesFrom } from '../../src/graph/structural-access.js';
import { addClusters } from '../../src/grouping/clusters-orchestration.js';
import { addSequences } from '../../src/grouping/sequences-mutation.js';
import { joinDistancedClusters } from '../../src/grouping/join.js';
import { assign, candidates, place as placeHierarchy, removeIsolatedMemberships } from '../../src/hierarchy/index.js';
import { MAX_TRANSACTION_WORK_UNITS } from '../../src/limits/constants.js';
import { contextWithTransactionWorkGuard } from '../../src/limits/transaction-guard.js';
import { backgroundWorkContext } from '../../src/limits/work-context.js';
import { WorkGuard } from '../../src/limits/work-guard.js';
import { orientationContext, orientSourceInterior } from '../../src/placement/container-orientation.js';
import { prescale } from '../../src/placement/prescale.js';
import { place, prepare } from '../../src/placement/structural-placement.js';
import { addHubs } from '../../src/proximity/hubs.js';
import { GoRand } from '../../src/random/go-math-rand.js';
import { preprocess as preprocessTrees } from '../../src/trees/index.js';

const fixture = JSON.parse(
  readFileSync(new URL('../fixtures/go-slice46-placement-reference.json', import.meta.url), 'utf8'),
);
const bg = backgroundWorkContext();

// ── Builders (mirror s46Spec.build / preprocess) ─────────────────────────────

function build(spec) {
  const g = new Graph();
  g.CellSize = spec.cellSize ?? 0;
  const nodes = new Map();
  const order = [];
  for (const ns of spec.nodes ?? []) {
    const n = new Node(BigInt(ns.id), ns.w, ns.h);
    if (ns.shape) n.SetShape(ns.shape);
    if (ns.fixed) n.FixedTopLeft = new Point(ns.fx ?? 0, ns.fy ?? 0);
    if (ns.placed) n.TopLeft = new Point(ns.x ?? 0, ns.y ?? 0);
    if (ns.label) {
      n.Label = new Label(String(ns.id), ns.label.w, ns.label.h);
      n.Label.Position = ns.label.pos ?? 0;
      if (ns.label.fixed) n.Label.FixPosition();
    }
    if (ns.fontSize) n.FontSize = ns.fontSize;
    n.IsMultiple = Boolean(ns.multiple);
    const container = ns.container ? nodes.get(ns.container) : null;
    g.AddNewNodeToContainer(container, n);
    nodes.set(ns.id, n);
    order.push(n);
  }
  for (const es of spec.edges ?? []) {
    const e = g.Connect(nodes.get(es.from), nodes.get(es.to));
    if (es.directed) {
      e.SourceArrowhead = 'none';
      e.TargetArrowhead = 'triangle';
    }
  }
  for (const [a, b] of spec.nears ?? []) nodes.get(a).AddNear(nodes.get(b));
  for (const d of spec.directions ?? []) {
    g.Directions.set(d.container ? nodes.get(d.container) : null, d.orientation);
  }
  return { g, nodes, order };
}

function preprocessSpec(spec, b, seed) {
  const random = new GoRand(seed);
  const hierarchyRandom = new GoRand(seed);
  prescale(b.g);
  if (spec.sequences) addSequences(bg, b.g, random);
  prepare(b.g);
  if (spec.trees) preprocessTrees(bg, b.g);
  if (spec.hierarchy) {
    assign(bg, b.g, null, candidates(b.g));
    placeHierarchy(bg, b.g, null, hierarchyRandom);
    removeIsolatedMemberships(b.g);
  }
  if (spec.clusters) addClusters(bg, b.g, seed, random);
  if (spec.hubs) addHubs(bg, b.g);
}

// ── Observations (mirror s46Universe / s46Geom / s46Observe) ────────────────

function universe(b) {
  const seen = new Set();
  const out = [];
  const add = (n) => {
    if (n != null && !seen.has(n)) {
      seen.add(n);
      out.push(n);
    }
  };
  for (const n of b.order) add(n);
  for (const n of b.g.Nodes) {
    add(n);
    for (const d of b.g.AllDescendantNodes(n, true)) add(d);
  }
  return out
    .map((n, i) => [n, i])
    .sort((x, y) => (x[0].ID < y[0].ID ? -1 : x[0].ID > y[0].ID ? 1 : x[1] - y[1]))
    .map(([n]) => n);
}

function geom(b) {
  const out = [];
  for (const n of universe(b)) {
    if (n.TopLeft == null) out.push(Number(n.ID), 0, 0, 0, n.Width, n.Height);
    else out.push(Number(n.ID), 1, n.TopLeft.X, n.TopLeft.Y, n.Width, n.Height);
  }
  return out;
}

function edgeList(g) {
  const out = [];
  for (const e of g.Edges) out.push(Number(e.From.ID), Number(e.To.ID));
  return out;
}

function features(b) {
  const f = { trees: b.g.Trees.size, sequences: b.g.Sequences.size, clusters: b.g.Clusters.size, hierarchies: 0, herds: 0, hubs: b.g.Hubs.size };
  for (const n of universe(b)) {
    if (n.Hierarchy != null) f.hierarchies++;
    if (n.HerdAssignment != null) f.herds++;
  }
  return f;
}

function ownedOK(b) {
  for (const n of b.g.Nodes) {
    if (n.Graph !== b.g) return false;
    for (const d of b.g.AllDescendantNodes(n, true)) if (d.Graph !== b.g) return false;
  }
  return true;
}

function captureOwners(b) {
  const nodes = universe(b);
  const graphs = nodes.map((n) => n.Graph);
  return { restored: () => nodes.every((n, i) => n.Graph === graphs[i]) };
}

function countingContext(cancel = 0, panicAt = 0) {
  return {
    calls: 0,
    Err() {
      this.calls++;
      if (panicAt > 0 && this.calls === panicAt) throw 's46 injected panic';
      if (cancel > 0 && this.calls >= cancel) return COUNTING_CANCELED;
      return null;
    },
  };
}
const COUNTING_CANCELED = new Error('context canceled');

function limitGuard(limit) {
  const guard = new WorkGuard(bg, 'Slice44PlacementOracle', BigInt(limit));
  return [guard, contextWithTransactionWorkGuard(bg, guard)];
}

function errorString(err) {
  if (err == null) return '';
  return typeof err === 'string' ? err : err.message;
}

function runPlace(spec, seed, ctx) {
  const b = build(spec);
  preprocessSpec(spec, b, seed);
  const owners = captureOwners(b);
  const pre = features(b);
  const priorCUS = new Map();
  b.g.CommonUncleSiblings = priorCUS;
  let err = null;
  let panicked = '';
  try {
    place(ctx, b.g, seed);
  } catch (e) {
    if (typeof e === 'string') panicked = e;
    else err = e;
  }
  pre.herds = features(b).herds;
  const result = {
    error: errorString(err),
    cellSize: b.g.CellSize,
    cusNil: b.g.CommonUncleSiblings == null,
    ownedOK: false,
    features: pre,
  };
  if (err == null && panicked === '') {
    result.geom = geom(b);
    result.edges = edgeList(b.g);
    result.ownedOK = ownedOK(b);
  }
  return { b, result, panicked, ownersOK: owners.restored(), cusRestored: b.g.CommonUncleSiblings === priorCUS };
}

function expectResult(actual, expected) {
  expect(actual.error).toBe(expected.error);
  expect(actual.cellSize).toBe(expected.cellSize);
  expect(actual.cusNil).toBe(expected.cusNil);
  expect(actual.features).toEqual(expected.features);
  if (expected.error === '') {
    expect(actual.ownedOK).toBe(expected.ownedOK);
    expect(actual.edges ?? []).toEqual(expected.edges ?? []);
    expect(actual.geom).toEqual(expected.geom ?? []);
  }
}

// ── Place ────────────────────────────────────────────────────────────────────

describe('Slice 46 oracle — Place', () => {
  const groups = new Set(fixture.place.map((c) => c.group));
  it('covers every required placement group', () => {
    for (const group of [
      'empty', 'singleton', 'fixed singleton', 'nested container', 'tree + ordinary nodes',
      'hierarchy members', 'cluster', 'sequence', 'Near', 'Herd', 'fixed child obstacles',
      'edge abduction', 'seeded determinism',
    ]) {
      expect(groups.has(group)).toBe(true);
    }
  });

  for (const c of fixture.place) {
    describe(`${c.group}: ${c.name}`, () => {
      it('matches pinned geometry, edges, ownership, and CommonUncleSiblings', () => {
        const first = runPlace(c.spec, c.seed, bg);
        expectResult(first.result, c.result);
        const second = runPlace(c.spec, c.seed, bg);
        expect(second.result).toEqual(first.result);
      });

      if (c.errCalls >= 0) {
        it('performs the pinned number of context checks', () => {
          const ctx = countingContext();
          const run = runPlace(c.spec, c.seed, ctx);
          expect(run.result.error).toBe('');
          expect(ctx.calls).toBe(c.errCalls);
        });
      }

      if (c.probes?.length) {
        it('restores ownership and CommonUncleSiblings on cancellation', () => {
          for (const p of c.probes) {
            const run = runPlace(c.spec, c.seed, countingContext(p.at));
            expect({ at: p.at, error: run.result.error }).toEqual({ at: p.at, error: p.error });
            expect(run.ownersOK).toBe(p.ownersOK);
            expect(run.cusRestored).toBe(p.cusRestored);
          }
        });
      }

      if (c.panics?.length) {
        it('restores ownership and CommonUncleSiblings on panic', () => {
          for (const p of c.panics) {
            const run = runPlace(c.spec, c.seed, countingContext(0, p.at));
            expect({ at: p.at, error: run.result.error, panic: run.panicked }).toEqual({
              at: p.at,
              error: p.error,
              panic: p.panic ?? '',
            });
            expect(run.ownersOK).toBe(p.ownersOK);
            expect(run.cusRestored).toBe(p.cusRestored);
          }
        });
      }

      if (c.limit) {
        it('matches the transaction-guard W/W−1 boundary', () => {
          const [guard, ctx] = limitGuard(MAX_TRANSACTION_WORK_UNITS);
          expect(runPlace(c.spec, c.seed, ctx).result.error).toBe('');
          expect(Number(guard.Used())).toBe(c.limit.w);
          if (c.limit.w === 0) return;
          const [guardW, ctxW] = limitGuard(c.limit.w);
          expect(runPlace(c.spec, c.seed, ctxW).result.error).toBe('');
          expect(Number(guardW.Used())).toBe(c.limit.w);
          const [guard1, ctx1] = limitGuard(c.limit.w - 1);
          const run = runPlace(c.spec, c.seed, ctx1);
          expect(run.result.error).toBe(c.limit.wMinus1Error);
          expect(Number(guard1.Used())).toBe(c.limit.usedAtWMinus1);
          expect(run.ownersOK).toBe(c.limit.ownersOK);
          expect(run.cusRestored).toBe(c.limit.cusRestored);
        });
      }
    });
  }
});

// ── JoinDistancedClusters ────────────────────────────────────────────────────

function runJoin(spec, ctx) {
  const b = build(spec);
  const before = geom(b);
  let err = null;
  try {
    joinDistancedClusters(ctx, b.g);
  } catch (e) {
    err = e;
  }
  return { b, before, err };
}

describe('Slice 46 oracle — JoinDistancedClusters', () => {
  for (const c of fixture.join) {
    it(c.name, () => {
      let guard = null;
      let ctx = bg;
      if (c.shared) [guard, ctx] = limitGuard(MAX_TRANSACTION_WORK_UNITS);
      const run = runJoin(c.spec, ctx);
      expect(errorString(run.err)).toBe(c.error);
      expect(geom(run.b)).toEqual(c.geom);
      expect(JSON.stringify(run.before) !== JSON.stringify(geom(run.b))).toBe(c.changed);
      if (guard) expect(Number(guard.Used())).toBe(c.used);
      if (c.limit) {
        const [g1, ctx1] = limitGuard(c.limit.w - 1);
        const r1 = runJoin(c.spec, ctx1);
        expect(errorString(r1.err)).toBe(c.limit.wMinus1Error);
        expect(Number(g1.Used())).toBe(c.limit.usedAtWMinus1);
        expect(JSON.stringify(r1.before) === JSON.stringify(geom(r1.b))).toBe(c.limit.ownersOK);
      }
      const counter = countingContext();
      expect(runJoin(c.spec, counter).err).toBeNull();
      expect(counter.calls).toBe(c.errCalls);
      for (const p of c.probes ?? []) {
        const rp = runJoin(c.spec, countingContext(p.at));
        expect({ at: p.at, error: errorString(rp.err) }).toEqual({ at: p.at, error: p.error });
        expect(JSON.stringify(rp.before) === JSON.stringify(geom(rp.b))).toBe(p.ownersOK);
      }
    });
  }
});

// ── Container orientation ───────────────────────────────────────────────────

function runOrient(spec, rootID, disabled, ctx) {
  const b = build(spec);
  const root = b.nodes.get(rootID);
  const inner = newGraph();
  copyEntitiesFrom(inner, b.g);
  inner.CellSize = b.g.CellSize;
  for (const child of b.g.Containers.get(root) ?? []) inner.AddNodeUnchecked(child);
  for (const e of b.g.Edges) {
    if (e.From.Container === root && e.To.Container === root) inner.AddEdge(e);
  }
  const before = geom(b);
  let err = null;
  try {
    let runCtx = ctx;
    if (disabled) runCtx = orientationContext(ctx, b.g);
    orientSourceInterior(runCtx, inner, root, null);
  } catch (e) {
    err = e;
  }
  return { b, before, err };
}

describe('Slice 46 oracle — container orientation', () => {
  for (const c of fixture.orientation) {
    it(c.name, () => {
      const run = runOrient(c.spec, c.root, c.disabled, bg);
      expect(errorString(run.err)).toBe(c.error);
      expect(geom(run.b)).toEqual(c.geom);
      const counter = countingContext();
      expect(runOrient(c.spec, c.root, c.disabled, counter).err).toBeNull();
      expect(counter.calls).toBe(c.errCalls);
      for (const p of c.probes ?? []) {
        const rp = runOrient(c.spec, c.root, c.disabled, countingContext(p.at));
        expect({ at: p.at, error: errorString(rp.err) }).toEqual({ at: p.at, error: p.error });
        expect(JSON.stringify(rp.before) === JSON.stringify(geom(rp.b))).toBe(p.ownersOK);
      }
    });
  }
});

// ── Prepare ──────────────────────────────────────────────────────────────────

function loopOffset(offsets, side) {
  if (offsets instanceof Map) return offsets.get(side) ?? 0;
  return offsets[side] ?? 0;
}

describe('Slice 46 oracle — Prepare', () => {
  for (const c of fixture.prepare) {
    it(c.name, () => {
      const b = build(c.spec);
      prescale(b.g);
      prepare(b.g);
      const labels = [];
      const loops = [];
      for (const n of b.order) {
        if (n.Label != null) labels.push(Number(n.ID), n.Label.Position, n.Label.PositionFixed() ? 1 : 0);
        const offsets = n.LoopOffsets;
        const size = offsets == null ? 0 : offsets instanceof Map ? offsets.size : Object.keys(offsets).length;
        if (size > 0) {
          loops.push(
            Number(n.ID),
            loopOffset(offsets, Orientation.Top),
            loopOffset(offsets, Orientation.Right),
            loopOffset(offsets, Orientation.Bottom),
            loopOffset(offsets, Orientation.Left),
          );
        }
      }
      expect(labels).toEqual(c.labels ?? []);
      expect(loops).toEqual(c.loops ?? []);
      expect(geom(b)).toEqual(c.geom);
    });
  }
});
